# Generated by Django 4.0.3 on 2022-06-12 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='item',
            new_name='task',
        ),
    ]
