//auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const REGISTER_SUCCESS="REGISTER_SUCCESS"
export const REGISTER_FAIL="REGISTER_FAIL"
//projects
export const PROJECT_CREATED="PROJECT_CREATED"
export const PROJECT_CREATED_FAIL="PROJECT_CREATED_FAIL"
export const PROJECTS_LOADED_SUCCESS="PJOJECTS_LOADED_SUCCESS"
export const PROJECTS_LOADED_FAIL="PJOJECTS_LOADED_FAIL"
export const DESTROY_PROJECTS ="DESTROY_PROJECTS" 
export const PROJECT_LOADED_SUCCESS = "PROJECT_LOADED_SUCCESS"
export const PROJECT_LOADED_FAIL = "PROJECT_LOADED_FAIL"
export const PROJECT_EDIT_SUCCESS = "PROJECT_EDIT_SUCCESS"
export const PROJECT_EDIT_FAIL = "PROJECT_EDIT_FAIL"
export const PROJECT_DELETE_SUCCESS  = "PROJECT_DELETE_SUCCESS"
export const PROJECT_DELETE_FAIL = "PROJECT_DELETE_FAIL"

//boards
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS"
export const CREATE_BOARD_FAIL = "CREATE_BOARD_FAIL"
export const LOAD_BOARDS_FAIL = "LOAD_BOARDS_FAIL"
export const LOAD_BOARDS_SUCCESS = "LOAD_BOARDS_SUCCESS"
export const LOAD_CURRENT_BOARD_SUCCESS = "LOAD_CURRENT_BOARD_SUCCESS"
export const LOAD_CURRENT_BOARD_FAIL ="LOAD_CURRENT_BOARD_FAIL"
export const CREATE_TASK_SUCCESS ="CREATE_TASK_SUCCESS"
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL"
export const UPDATE_TASK_SUCCESS ="UPDATE_TASK_SUCCESS"
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL"



