//auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const REGISTER_SUCCESS="REGISTER_SUCCESS"
export const REGISTER_FAIL="REGISTER_FAIL"
//projects
export const PROJECT_CREATED="PROJECT_CREATED"
export const PROJECT_CREATED_FAIL="PROJECT_CREATED_FAIL"
export const PROJECTS_LOADED_SUCCESS="PJOJECTS_LOADED_SUCCESS"
export const PROJECTS_LOADED_FAIL="PJOJECTS_LOADED_FAIL"
export const DESTROY_PROJECTS ="DESTROY_PROJECTS" 
export const PROJECT_LOADED_SUCCESS = "PROJECT_LOADED_SUCCESS"
export const PROJECT_LOADED_FAIL = "PROJECT_LOADED_FAIL"
//boards
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS"
export const CREATE_BOARD_FAIL = "CREATE_BOARD_FAIL"
export const LOAD_BOARDS_FAIL = "LOAD_BOARDS_FAIL"
export const LOAD_BOARDS_SUCCESS = "LOAD_BOARDS_SUCCESS"



